UPSTREAM: Input: mousedev - fix implicit conversion warning
Clang warns:

drivers/input/mousedev.c:653:63: error: implicit conversion from 'int'
to 'signed char' changes value from 200 to -56
[-Wconstant-conversion]
  client->ps2[1] = 0x60; client->ps2[2] = 3; client->ps2[3] = 200;
                                                            ~ ^~~
As the PS2 data is really a stream of bytes, let's switch to using u8 type
for it, which silences this warning.

Change-Id: I4957cb24ec0b4622c664820430a57be796fe2279
Signed-off-by: Nick Desaulniers <nick.desaulniers@gmail.com>
Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>
(cherry picked from commit dae1a432ab1fe79ae53129ededeaece35a2dc14d)
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>